/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <GREEN.h>
#include <GREEN_aliases.h>
#include <RED.h>
#include <RED_aliases.h>
#include <Sensor_ADC.h>
#include <Accel_Z.h>
#include <Accel_Z_aliases.h>
#include <Accel_Y.h>
#include <Accel_Y_aliases.h>
#include <Accel_X.h>
#include <Accel_X_aliases.h>
#include <BLUE.h>
#include <BLUE_aliases.h>
#include <Sensor_ADC_IRQ.h>
#include <Sensor_ADC_intClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

